spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  redis:
    port: 6379
    host: redis.redis.svc.cluster.local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessExpiredExp: ${JWT_ACCESS_EXP}
  refreshExpiredExp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
gpt:
  secret: ${GPT_SECRET}
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: mukgen
    region:
      static: ap-northeast-2
    stack:
      auto: false

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus

flarelane:
  segments-id: ${SEGMENTS_ID}
  api-secret-key: ${FLARELANE_API_KEY}

server:
  port: 8080

