spring:
  datasource:
    driver-class-name: ${DRIVER}
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}



logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace