spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

info:
  oauth:
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    redirectUri: ${REDIRECT_URI}

jwt:
  secretKey: ${JWT_SECRET_KEY:asdjfkasdhfjkashdfkashdfkahsdjkfahskdf}
  accessExpiredExp: ${JWT_ACCESS_EXP:1800000}
  refreshExpiredExp: ${JWT_REFRESH_EXP:432000000}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}

logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
gpt:
  secret: ${GPT_SECRET}
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: mukgen
    region:
      static: ap-northeast-2
    stack:
      auto: false

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus

server:
  port: 80
