name Codecov
on
  push
    branches
      - develop
      - feature
  pull_request
    branches
      - develop
      - feature
jobs
  build
    runs-on ubuntu-latest
    steps
      - uses actions/checkout@v2
      - name Install dependencies
        run |
          sudo apt-get update
          sudo apt-get install -y build-essential lcov gcovr
      - name Build project
        run |
          mkdir build
          cd build
          cmake ..
          make
      - name Run tests
        run |
          ./build/test
      - name Upload coverage to Codecov
        uses codecov/codecov-action@v2.1.0
        with
          token ${{ secrets.CODECOV_TOKEN }}
